# Generated by Django 3.0.5 on 2020-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Status_Update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage',
            name='team',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
